version: "3.8"
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
#    build:
#      context: ./sentinel
    networks:
      - ebookdownload
    volumes:
      - ./redis/sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
#    build:
#      context: ./sentinel
    networks:
      - ebookdownload
    volumes:
      - ./redis/sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
#    build:
#      context: ./sentinel
    networks:
      - ebookdownload
    volumes:
      - ./redis/sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
networks:
  ebookdownload:
